// Command debux-docs generates command and RBAC references from the same
// metadata used by the CLI and doctor. Run with --check in CI to detect drift.
package main

import (
	"bytes"
	"fmt"
	"os"
	"strings"

	"github.com/clement-tourriere/debux/internal/cli"
	"github.com/clement-tourriere/debux/internal/runtime"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

func main() {
	check := len(os.Args) > 1 && os.Args[1] == "--check"
	files := map[string]string{"docs/reference.md": commandReference(), "docs/rbac.md": rbacReference()}
	for path, body := range files {
		body = strings.TrimRight(body, "\n") + "\n"
		if check {
			current, err := os.ReadFile(path)
			if err != nil || string(current) != body {
				fmt.Fprintf(os.Stderr, "%s is stale; run go run ./cmd/debux-docs\n", path)
				os.Exit(1)
			}
		} else if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
	}
}

func commandReference() string {
	var out bytes.Buffer
	out.WriteString("# CLI reference\n\nGenerated by `go run ./cmd/debux-docs`; do not edit by hand.\n\n")
	var visit func(*cobra.Command)
	visit = func(cmd *cobra.Command) {
		if cmd.Hidden {
			return
		}
		fmt.Fprintf(&out, "## `%s`\n\n%s\n\n```text\n%s\n```\n\n", cmd.CommandPath(), cmd.Short, cmd.UseLine())
		if cmd.Flags().HasFlags() {
			out.WriteString("| Flag | Default | Description |\n|---|---|---|\n")
			cmd.Flags().VisitAll(func(flag *pflag.Flag) {
				if flag.Hidden {
					return
				}
				name := "--" + flag.Name
				if flag.Shorthand != "" {
					name += ", -" + flag.Shorthand
				}
				fmt.Fprintf(&out, "| `%s` | `%s` | %s |\n", name, escape(flag.DefValue), escape(flag.Usage))
			})
			out.WriteString("\n")
		}
		for _, child := range cmd.Commands() {
			visit(child)
		}
	}
	visit(cli.NewRootCmd())
	return out.String()
}

func escape(s string) string { return strings.NewReplacer("|", "\\|", "\n", " ", "`", "'").Replace(s) }

func rbacReference() string {
	var out bytes.Buffer
	out.WriteString("# Kubernetes RBAC by operation\n\nGenerated from `runtime.KubernetesPermissions`, also used by `debux doctor --mode`.\nDo not edit the permission tables by hand.\n\nProfiles select Linux privileges; they do not change API permissions. Bind only the roles needed for your operation, in the namespace you intend to debug. These examples create roles, not role bindings. Both POST (SPDY) and GET (WebSocket fallback) are listed for exec/attach.\n\n`cp` uses `ephemeral` permissions. Listing all namespaces additionally requires a cluster-scoped pod list permission. Optional event-list access improves failure diagnostics; it is not required to start a session.\n\n")
	for _, mode := range runtime.KubernetesOperationModes {
		fmt.Fprintf(&out, "## %s\n\n```sh\ndebux doctor --context CONTEXT --namespace prod --mode %s --strict\n```\n\n", mode, mode)
		permissions, err := runtime.KubernetesPermissions(mode)
		if err != nil {
			panic(err)
		}
		for _, cluster := range []bool{false, true} {
			groups := map[string][]string{}
			var resources []string
			for _, p := range permissions {
				if p.ClusterScoped != cluster {
					continue
				}
				name := p.Resource
				if p.Subresource != "" {
					name += "/" + p.Subresource
				}
				if _, ok := groups[name]; !ok {
					resources = append(resources, name)
				}
				groups[name] = append(groups[name], p.Verb)
			}
			if len(resources) == 0 {
				continue
			}
			kind := "Role"
			namespace := "  namespace: prod\n"
			if cluster {
				kind = "ClusterRole"
				namespace = ""
			}
			fmt.Fprintf(&out, "```yaml\napiVersion: rbac.authorization.k8s.io/v1\nkind: %s\nmetadata:\n  name: debux-%s\n%srules:\n", kind, mode, namespace)
			for _, resource := range resources {
				fmt.Fprintf(&out, "  - apiGroups: [\"\"]\n    resources: [%q]\n    verbs: [\"%s\"]\n", resource, strings.Join(groups[resource], "\", \""))
			}
			out.WriteString("```\n\n")
		}
	}
	return out.String()
}
